# Generated by Django 4.2.1 on 2023-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('payment_Status', models.BooleanField()),
                ('receipt', models.CharField(max_length=32)),
                ('payment_method', models.CharField(max_length=32)),
            ],
        ),
    ]
