# Generated by Django 4.2.1 on 2023-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=64)),
                ('date_of_shipment', models.DateTimeField(auto_now_add=True)),
                ('date_of_arrival', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=32)),
                ('delivery_person', models.CharField(max_length=32)),
            ],
        ),
    ]
