# Generated by Django 4.2.1 on 2023-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=32)),
                ('time_and_date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
